# Prometheus Configuration for FastAPI

# Global configuration
# The scrape_interval is set to every 5 seconds by default.
# You can change it according to your needs.

global:
  scrape_interval: 5s

# Scrape configuration for FastAPI
scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000'] # Replace with your FastAPI server address
